import { type NextPage } from "next";
import Head from "next/head";
import Link from "next/link";
import { SignInButton, SignOutButton, useUser } from "@clerk/nextjs"
import { SignIn } from "@clerk/nextjs"

import { RouterOutputs, api } from "~/utils/api";

const CreatePostWizard = () => {
  const { user } = useUser()

  if (!user) return null

  return (
    <div className="flex gap-4 w-full">
      <img className="rounded-full w-14" src={user.profileImageUrl} alt="profile image" />
      <input
        className="bg-transparent grow outline-none"
        type="text"
        placeholder="Type some emojis!"
      />
    </div>
  )
}

type PostWithUser = RouterOutputs["posts"]["getAll"][number]
const PostView = ({ post, author }: PostWithUser) => {
  return (
    <div key={post.id} className="border-b border-slate-400 p-8">
      <div>@{author.username}</div>
      {post.content}
    </div>
  )
}

const Home: NextPage = () => {
  const user = useUser()

  const { data, isLoading } = api.posts.getAll.useQuery()

  if (isLoading) return <div className="flex h-screen justify-center items-center">Loading...</div>

  if (!data) return <div className="flex h-screen justify-center items-center">Something went wrong 😕</div>
  
  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex h-screen justify-center">
        <div className="h-full w-full border-x border-slate-400 md:max-w-2xl">
          <div className="flex border-b border-slate-400 p-4">
            {!user.isSignedIn && (
              <div className="flex w-full justify-center">
                <div className="ml-auto py-1 px-2 border border-slate-400 rounded-lg">
                  <SignInButton/>
                </div>
              </div>
            )}
            {!!user.isSignedIn && (
              <div className="flex w-full justify-between items-center">
                <CreatePostWizard />
                <div className="py-1 px-2 border border-slate-400 rounded-lg">
                  <SignOutButton>SignOut</SignOutButton>
                </div>
              </div>
            )}
          </div>
          <div>
            {data?.map((fullPost) => (
              <PostView {...fullPost} />
            ))}
          </div>
        </div>
      </main>
    </>
  );
};

export default Home;
